#!/usr/bin/env bash
# cmds.sh - one-shot baseline enumeration.
#
# This is intentionally conservative: it discovers, scans, and enumerates. It
# does not attempt exploitation. Output is saved into the workspace folders.

set -euo pipefail
umask 077

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OSCP="$ROOT_DIR/scripts/oscp.sh"

[[ -x "$OSCP" ]] || { echo "[-] $OSCP not executable"; exit 1; }

export OSCP_YES=1

echo "[*] One-shot OSCP baseline from: $ROOT_DIR"
"$OSCP" status || true

echo "[*] Step 1/4: discovery"
"$OSCP" discover || echo "[!] discover failed; continuing"

echo "[*] Step 2/4: light scan across live hosts"
"$OSCP" nmap-live || echo "[!] nmap-live failed; continuing"

echo "[*] Step 3/4: primary target full/deep scan"
if [[ -f "$ROOT_DIR/.oscp_env" ]]; then
  # .oscp_env is generated by init_oscp.sh as simple KEY=value assignments.
  while IFS='=' read -r key value; do
    key="${key#export }"
    value="${value%$'\r'}"
    case "$key" in
      OSCP_TARGET) OSCP_TARGET="$value" ;;
    esac
  done < <(grep -E '^(export )?OSCP_TARGET=' "$ROOT_DIR/.oscp_env" 2>/dev/null || true)
fi

if [[ -n "${OSCP_TARGET:-}" ]]; then
  "$OSCP" nmap-full "$OSCP_TARGET" || echo "[!] nmap-full failed; continuing"
  "$OSCP" nmap-deep "$OSCP_TARGET" || echo "[!] nmap-deep failed; continuing"

  echo "[*] Step 4/4: service-aware enumeration"
  "$OSCP" enum-all "$OSCP_TARGET" || echo "[!] enum-all failed; continuing"
else
  echo "[!] OSCP_TARGET is not set; skipping per-target scans"
fi

"$OSCP" status || true
echo "[+] One-shot baseline complete."
echo "[*] For report evidence, open the relevant output and run:"
echo "    ./scripts/oscp.sh screenshot \"proof with ip visible\""
